package hello.wantedpreonboarding.entity.enums;

public enum RegionType {
    SEOUL, BUSAN, DAEGU, INCHEON, GWANGJU, DAEJEON, ULSAN, SEJONG, GYEONGI, GANGWON, CHOONGBUK, CHOONGNAM, JEONBUK, JEONNAM, GYEONGBUK, GYEONGNAM, JEJU;
}
